# SPDX-FileCopyrightText: Copyright (c) 2024-2026 Almaz Ilaletdinov <a.ilaletdinov@yandex.ru>
# SPDX-License-Identifier: MIT
---
version: '3'

tasks:
  default:
    desc: "Build pipeline"
    deps: [install-deps,unit-tests,integration-tests,lint,build]

  build:
    desc: "Build the app"
    deps: [install-deps]
    cmds:
      - uv build

  install-deps:
    desc: "Install dependencies"
    cmds:
      - uv sync

  unit-tests:
    desc: "Run unit tests"
    cmds:
      - uv run pytest tests/unit

  integration-tests:
    desc: "Run integration tests"
    cmds:
      - uv run pytest tests/it -s

  fmt:
    desc: "Run formatters"
    cmds:
      - uv run isort ondivi tests
      - uv run ruff check ondivi tests --fix

  lint:
    desc: "Run linters"
    cmds:
      - uv run flake8 ondivi tests
      - uv run pylint ondivi tests
      - uv run mypy ondivi tests --strict

  clean:
    desc: "Clean caches"
    cmds:
      - git clean -f -d -x
